version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  fastapi_app:
    build: .
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_CHANNEL: "chat"
      REDIS_CLIENTS_KEY: "active_clients"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379